# Generated by Django 2.1.3 on 2018-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_state',
            field=models.IntegerField(choices=[(1, 'Open'), (3, 'In Review'), (4, 'Review Done'), (5, 'In Testing'), (6, 'Testing Done'), (7, 'Blocked'), (8, 'Pre Release'), (9, 'Released')], default=1),
        ),
    ]
