version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql
    ports:
    - "5432:5432"

  redis:
    image: redis:5.0.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
    - ./redis/data:/code/data
#    networks:
#      - newscast

  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./NodeMachine/Dockerfile
    command: bash -c "npm install & npm run develop"
    volumes:
      - .:/code
      - /code/nodemachine/node_modules
      - ./NodeMachine:/code/NodeMachine/:rw
